import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";

import { useAuthToken } from "../hooks/AuthToken";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { token, user, setToken, setUser } = useAuthToken();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="flex justify-center items-center">main page</h1>
      {token ? (
        <>
          <p>logged in as {user?.name}</p>
          <button
            onClick={async () => {
              try {
                const res = await axios.post(
                  process.env.NEXT_PUBLIC_BACKEND_DOMAIN + "/logout",
                  null,
                  { headers: { Authorization: `Bearer ${token}` } }
                );
                console.log(res.data);

                setToken!(null);
                setUser!(null);
              } catch (error) {
                console.log(error);
              }
            }}
          >
            log out
          </button>
        </>
      ) : null}
    </div>
  );
};

export default Home;
